### ISSUE TITLE
Turning off ghosts crashes game in edited levels

### ISSUE THREAD

**Issue by snailmusic** [HJfod/GPMods#1]
[ModLdr Latest]
If im playing one of my levels that i created and turn off ghosts, it crashes my game, though not in uploaded levels.

**Comment by HJfod** [comment]
Hello! I just pushed some changes to fix bugs, can you test and see if this bug still persists? (Follow instructions for installing development version)

**Comment by HJfod** [comment]
Just released v1.2 that should fix this :) Please report back if you're still experiencing this!

**Comment by snailmusic** [comment]
Nope! It was fixed! Thank you!
