### ISSUE TITLE
Opening levels with high object count crashes the game.

### ISSUE THREAD

**Issue by snailmusic** [HJfod/GPMods#2]
[MdLdr Latest]
I made sure it wasn't based on low detail mode with another level. This happens at least in the featured tab. Also made sure its not a problem with MdLdr but it could be a problem with MdLdr and GPMods together.

**Comment by HJfod** [comment]
This sounds like an issue with GD itself? Can you run high-object levels normally without crashes?

**Comment by snailmusic** [comment]
Yes, normally I can run them, but could it be RAM usage? I recently heard that there is a patch to allow GD more RAM.

**Comment by HJfod** [comment]
[4gb_patch.zip](https://github.com/HJfod/GPMods/files/6123574/4gb_patch.zip)
Yes there is, you can download it from here :)

**Comment by snailmusic** [comment]
I'll see if that was the problem!

**Comment by snailmusic** [comment]
It was the amount of ram!
